# Generated by Django 5.1.3 on 2024-12-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('male_name', models.CharField(blank=True, max_length=200)),
                ('female_name', models.CharField(blank=True, max_length=200)),
                ('reproductive_strategy', models.CharField(choices=[('HERMAPHRODITIC', 'Hermaphroditic'), ('DIOECIOUS', 'Dioecious'), ('SEQUENTIAL_HERMAPHRODITISM', 'Sequential Hermaphroditism'), ('SIMULTANEOUS_HERMAPHRODITISM', 'Simultaneous Hermaphroditism'), ('PARTHENOGENESIS', 'Parthenogenesis'), ('GYNOGENESIS', 'Gynogenesis'), ('HYBRIDOGENESIS', 'Hybridogenesis')], max_length=50)),
                ('sex_determination', models.CharField(choices=[('GENETIC', 'Genetic'), ('ENVIRONMENTAL', 'Environmental'), ('HAPLO_DIPLOID', 'Haplo-diploid'), ('POLYGENIC', 'Polygenic'), ('EPIGENETIC', 'Epigenetic')], max_length=50)),
                ('domain', models.CharField(max_length=255)),
                ('kingdom', models.CharField(max_length=255)),
                ('phylum', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
